let express = require("express");

let app = express();

let path = require("path");

let bodyParser = require("body-parser");

app.use(bodyParser.urlencoded({extended: true}));

app.use(express.static(path.join(__dirname, 'static')));

app.set("views", path.join(__dirname, "./views"));
app.set("view engine", "ejs");

require("./server/config/routes.js")(app);

let server = app.listen(3316, () => {
	console.log("App listening on port 3316");
});

let io = require("socket.io").listen(server);

io.sockets.on("connection", (socket) => {
	console.log("We are using sockets!!!");
	console.log(socket.id);

	socket.on("button_clicked", (data) => {
		console.log("Someone clicked a button. Reason: " + data.reason);
		socket.emit("server_response", {response: "sockets are the best!"})
	})
	socket.on("posting_form", (data) => {
		console.log(data);
		let randNum = Math.floor(Math.random()*1001)
		socket.emit("return_results", {response: "You emitted the following information to the server:{name:" + data.name + ", location:" + data.location + ", language: " + data.language + ", comments: " + data.comments + "} Your lucky number generated by the server is: " + randNum} )
	})
})
